USE eStore;

DROP TABLE IF EXISTS `USERS`;
DROP TABLE IF EXISTS `CHAT_LOG`;
DROP TABLE IF EXISTS `MESSAGE`;
DROP TABLE IF EXISTS `CATEGORY`;
DROP TABLE IF EXISTS `MOTORCYCLE`;
DROP TABLE IF EXISTS `ORDERS`;
DROP TABLE IF EXISTS `ORDER_ITEM`;

CREATE TABLE USERS(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* ATTRIBUTES */
    username VARCHAR(20) NOT NULL UNIQUE,
    password_key VARCHAR(64) NOT NULL,
    email VARCHAR(32) NOT NULL,
    user_role ENUM('Admin','Assistant','Customer') NOT NULL
);

CREATE TABLE CHAT_LOG(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* FK */
    customer_id INT REFERENCES USERS(id),
    assistant_id INT REFERENCES USERS(id)
);

CREATE TABLE MESSAGE(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* ATTRIBUTES */
    content TEXT NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    /* FK */
    sender_id INT REFERENCES USERS(id),
    chat_id INT REFERENCES CHAT_LOG(id)
);

CREATE TABLE CATEGORY(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* ATTRIBUTES */
    name ENUM('Sport Bike', 'Touring', 'Motocross', 'Scooter', 'Naked', 'Cruiser')
);

CREATE TABLE MOTORCYCLE(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* ATTRIBUTES */
    bike_brand VARCHAR(32) NOT NULL,
    bike_type VARCHAR(32) NOT NULL,
    bike_year INT NOT NULL,
    in_stock_ammount INT NOT NULL, 
    price INT NOT NULL,

    /* FK */
    bike_category INT REFERENCES CATEGORY(id)
);

CREATE TABLE ORDERS(
    /* PK */
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    /* ATTRIBUTES */
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    /* FK */
    user_id INT REFERENCES USERS(id)
);

CREATE TABLE ORDER_ITEM(
    /* PK */
    id INT AUTO_INCREMENT PRIMARY KEY,

    /* FK */
    bike_id INT REFERENCES MOTORCYCLE(id),
    order_id INT REFERENCES ORDERS(id)
);